language: node_js
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_2caea44aff20_key -iv $encrypted_2caea44aff20_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- npm install -g hexo-cli@1.1.0
install:
- npm install
script:
- hexo clean
- hexo generate
after_success:
- scp -o stricthostkeychecking=no -r public/* root@212.64.80.113:~/var/www/my-blog
